development:
  adapter: mysql
  encoding: utf8
  database: simpleclouding_development
  username: root
  password: 
  socket: /tmp/mysql.sock
  encoding: utf8

test:
  adapter: mysql
  encoding: utf8
  database: simpleclouding_test
  username: root
  password: 
  socket: /tmp/mysql.sock 
  encoding: utf8

production:
  development

cucumber:
  test